"""Render audit results to a client-ready Markdown report (optional PDF)."""

from __future__ import annotations

from datetime import date

from .model import AuditResult

_SEV_LABEL = {
    "critical": "CRITICAL",
    "high": "HIGH",
    "medium": "MEDIUM",
    "low": "LOW",
}

DISCLAIMER = (
    "This report is generated by an automated, rule-based analysis of the data "
    "exports provided. Estimated leakage figures are directional models based on "
    "the supplied data and industry benchmarks, not guaranteed savings. Findings "
    "should be validated against account context before acting."
)


def _section(result: AuditResult) -> list[str]:
    title = "Paid Ads — Spend Leakage" if result.kind == "ads" else "Organic — SEO / Search Console"
    out = [f"## {title}", "", f"**Health score: {result.score}/100**", ""]

    out.append("| Metric | Value |")
    out.append("| --- | --- |")
    for k, v in result.summary.items():
        label = k.replace("_", " ").title()
        out.append(f"| {label} | {v:,} |" if isinstance(v, (int, float)) else f"| {label} | {v} |")
    out.append("")

    if result.total_leakage > 0:
        out.append(
            f"**Modeled recoverable spend: ${result.total_leakage:,.0f} / month**\n"
        )

    if not result.findings:
        out.append("_No material issues detected in the supplied data._\n")
        return out

    for i, f in enumerate(result.sorted_findings(), 1):
        out.append(f"### {i}. [{_SEV_LABEL[f.severity]}] {f.title}")
        out.append("")
        out.append(f.detail)
        out.append("")
        if f.estimated_monthly_leakage > 0:
            out.append(
                f"- _Estimated monthly impact: ${f.estimated_monthly_leakage:,.0f}_"
            )
        out.append(f"- **Recommendation:** {f.recommendation}")
        out.append("")
    return out


def render_markdown(results: list[AuditResult], *, client: str) -> str:
    crit = sum(1 for r in results for f in r.findings if f.severity == "critical")
    high = sum(1 for r in results for f in r.findings if f.severity == "high")
    leak = sum(r.total_leakage for r in results)
    avg = round(sum(r.score for r in results) / len(results)) if results else 100

    lines = [
        f"# AI Account Health Check — {client}",
        f"_Generated {date.today().isoformat()}_",
        "",
        "## Executive Summary",
        "",
        f"- **Overall health score:** {avg}/100",
        f"- **Critical issues:** {crit}  |  **High-priority issues:** {high}",
        f"- **Modeled recoverable spend:** ${leak:,.0f} / month",
        "",
        "Top priorities:",
        "",
    ]
    top = sorted(
        (f for r in results for f in r.findings),
        key=lambda f: ({"critical": 0, "high": 1, "medium": 2, "low": 3}[f.severity],
                        -f.estimated_monthly_leakage),
    )[:3]
    lines += [f"{i}. **{f.title}** — {f.recommendation}" for i, f in enumerate(top, 1)] or [
        "_No critical issues found._"
    ]
    lines.append("")

    for r in results:
        lines += _section(r)

    lines += ["---", "", "### Methodology & Limitations", "", DISCLAIMER, ""]
    return "\n".join(lines)


def render_pdf(markdown_text: str, path: str) -> bool:
    """Render to PDF if reportlab is available. Returns False if it is not."""
    try:
        from reportlab.lib.pagesizes import LETTER
        from reportlab.lib.styles import getSampleStyleSheet
        from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer
    except ImportError:
        return False

    styles = getSampleStyleSheet()
    doc = SimpleDocTemplate(path, pagesize=LETTER, title="AI Account Health Check")
    flow = []
    for raw in markdown_text.splitlines():
        line = raw.rstrip()
        if not line:
            flow.append(Spacer(1, 6))
        elif line.startswith("# "):
            flow.append(Paragraph(line[2:], styles["Title"]))
        elif line.startswith("## "):
            flow.append(Paragraph(line[3:], styles["Heading2"]))
        elif line.startswith("### "):
            flow.append(Paragraph(line[4:], styles["Heading3"]))
        else:
            safe = line.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
            safe = safe.replace("**", "").replace("_", "")
            flow.append(Paragraph(safe, styles["BodyText"]))
    doc.build(flow)
    return True
